add linter files
Alabi12/Leaderboard pull request #1
Opened 2022-11-15 13:40 UTC by Alabi12

add inter files to the project

2022-11-15 23:42 UTC, zieeco requested changes
Hi @Alabi12 ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 23:42 UTC, zieeco commented on dist/index.html
> +            <li class="list-item">Name: 90</li>
- Hey, this part should be populated using javascript as this was not stated in the requirement, please, kindly bear this in mind as I'd mark it optional.

2022-11-15 23:42 UTC, zieeco commented on src/style.css
> +}
- Please let's kindly improve our design on this part to match the wireframe as much as we can. see the images below:


*wireframe*
![Screenshot from 2022-11-16 00-36-03](https://user-images.githubusercontent.com/59397159/202047766-6c7057e9-50ab-44ab-860d-f7314d0dd264.png)

*your design*
![Screenshot from 2022-11-16 00-34-47](https://user-images.githubusercontent.com/59397159/202047773-589d15a0-47e6-43a1-a2cd-50da71a06a4c.png)

2022-11-16 09:03 UTC, gemmen29 approved these changes
Hi @Alabi12, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 20:02 UTC, AmaduKamara approved these changes
# Status: APPROVED 🟢🟢🟢 

Hi @Alabi12,

Your project is complete!  

![ClappingLeonardoDicaprioGIF (3)](https://user-images.githubusercontent.com/50941074/202282299-bd246f58-4729-403a-96ba-4daaab0b1c46.gif)

## Highlights:
✅ You used Gitflow correctly
✅ Linter checks passed 
✅ Used async and await and arrow functions when fetching and posting score data to the API 👍 

There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-11-17 08:22 UTC, merged